const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');
const FORMS=['past','passivePast','present','passivePresent'];
const FORM_DIRS={past:'01-Active-Past',passivePast:'02-Passive-Past',present:'03-Active-Present',passivePresent:'04-Passive-Present'};
const ROW_COUNT=14;
async function generateFixture(page,form,section='section01'){await page.goto('/');await page.fill('#root-one','خ');await page.fill('#root-two','ر');await page.fill('#root-three','ج');await page.selectOption('#bab','نَصَرَ-يَنْصُرُ');await page.click('#sarf-form button[type="submit"]');await expect(page.locator('#explanation-panel')).toBeVisible();await page.selectOption('#explanation-section',section);await page.selectOption('#explanation-field',form);await expect(page.locator('#explanation-row option')).toHaveCount(ROW_COUNT)}
async function chooseRow(page,rowIndex){const value=await page.locator('#explanation-row option').nth(rowIndex).getAttribute('value');if(value===null)throw new Error(`Missing value for explanation row ${rowIndex}`);await page.evaluate(({nextValue})=>{const s=document.querySelector('#explanation-row');s.value=nextValue;s.dispatchEvent(new Event('change',{bubbles:true}))},{nextValue:value});await expect(page.locator('#explanation-row')).toHaveValue(value);await expect(page.locator('#explanation-output .structure-run').first()).toBeVisible();return value}
function safeName(value){return String(value).replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')||'row'}
async function labelsFor(page){return(await page.locator('#explanation-output .structure-run__label').allTextContents()).map(x=>x.trim())}
function hasPrefixLabel(labels,person,detail){return labels.some(l=>l.includes(`Muḍāriʿ prefix for the ${person} person`)&&l.includes(detail))}
function assertPrefix(labels,rowIndex){expect(labels.some(l=>l.includes('Muḍāriʿ prefix'))).toBeTruthy();if([0,1,2].includes(rowIndex))expect(hasPrefixLabel(labels,'third','masculine')).toBeTruthy();if([3,4,5].includes(rowIndex))expect(hasPrefixLabel(labels,'third','feminine')).toBeTruthy();if([6,7,8].includes(rowIndex))expect(hasPrefixLabel(labels,'second','masculine')).toBeTruthy();if([9,10,11].includes(rowIndex))expect(hasPrefixLabel(labels,'second','feminine')).toBeTruthy();if(rowIndex===12)expect(hasPrefixLabel(labels,'first','singular')).toBeTruthy();if(rowIndex===13)expect(hasPrefixLabel(labels,'first','plural')).toBeTruthy()}
async function assertPastLabels(page,rowIndex){const labels=await labelsFor(page);if(rowIndex>=6)expect(labels.some(l=>/^Subject\s+ت\b/i.test(l))).toBeFalsy();if(rowIndex===11){expect(labels.some(l=>l.includes('feminine plural addressee subject ending'))).toBeTruthy();expect(labels.some(l=>l.includes('feminine plural addressee ending'))).toBeTruthy()}if(rowIndex===12)expect(labels.some(l=>l.includes('first-person singular subject ending with ḍammah'))).toBeTruthy();if(rowIndex===13)expect(labels.some(l=>l.includes('first-person plural subject ending'))).toBeTruthy()}
async function assertPresentLabels(page,rowIndex){const labels=await labelsFor(page);assertPrefix(labels,rowIndex);const five=new Set([1,2,4,7,8,9,10]);if(five.has(rowIndex))expect(labels.some(l=>l.includes('retained nūn of the Five Verbs in the indicative')&&l.includes('ثبوت النون'))).toBeTruthy();if(rowIndex===5)expect(labels.some(l=>l.includes('feminine plural subject marker (نون النسوة)'))).toBeTruthy();if(rowIndex===11)expect(labels.some(l=>l.includes('feminine plural addressee subject marker (نون النسوة)'))).toBeTruthy()}
async function assertMajzumLabels(page,rowIndex){const labels=await labelsFor(page);assertPrefix(labels,rowIndex);expect(labels.some(l=>l.includes('jussive particle')&&l.includes('حرف جزم'))).toBeTruthy();const rule=await page.locator('#explanation-output .majzum-rule').textContent();const five=new Set([1,2,4,7,8,9,10]),niswa=new Set([5,11]);if(five.has(rowIndex)){expect(rule).toContain('Five Verbs');expect(rule).toContain('حذف النون')}else if(niswa.has(rowIndex)){expect(rule).toContain('نون النسوة');expect(rule).toContain('مبني على السكون');expect(rule).toContain('في محل جزم')}else expect(rule).toContain('علامة جزمه السكون')}
async function assertMansubLabels(page,rowIndex){const labels=await labelsFor(page);assertPrefix(labels,rowIndex);expect(labels.some(l=>l.includes('subjunctive particle')&&l.includes('حرف نصب'))).toBeTruthy();const rule=await page.locator('#explanation-output .mansub-rule').textContent();const five=new Set([1,2,4,7,8,9,10]),niswa=new Set([5,11]);if(five.has(rowIndex)){expect(rule).toContain('Five Verbs');expect(rule).toContain('حذف النون')}else if(niswa.has(rowIndex)){expect(rule).toContain('نون النسوة');expect(rule).toContain('مبني على السكون');expect(rule).toContain('في محل نصب')}else expect(rule).toContain('علامة نصبه الفتحة')}
async function assertHeavyLabels(page,rowIndex){const labels=await labelsFor(page);assertPrefix(labels,rowIndex);expect(labels.some(l=>l.includes('emphatic lām')&&l.includes('لام التوكيد'))).toBeTruthy();expect(labels.some(l=>l.includes('heavy-emphasis nūn')&&l.includes('نون التوكيد الثقيلة'))).toBeTruthy();const dual=new Set([1,4,7,10]),niswa=new Set([5,11]);if(dual.has(rowIndex)){expect(labels.some(l=>l.includes('dual')&&l.includes('ألف الاثنين'))).toBeTruthy();const heavyCards=page.locator('#explanation-output .structure-run').filter({hasText:'نون التوكيد الثقيلة'});await expect(heavyCards).toHaveCount(1)}if(niswa.has(rowIndex)){expect(labels.some(l=>l.includes('نون النسوة'))).toBeTruthy();expect(labels.some(l=>l.includes('الألف الفاصلة'))).toBeTruthy()}const rule=await page.locator('#explanation-output .heavy-rule').textContent();const derivation=await page.locator('#explanation-output .heavy-derivation').textContent();expect(rule).toContain('نون التوكيد الثقيلة');expect(derivation).toContain('نون التوكيد الثقيلة')}
async function shot(page,folder,rowIndex,rowValue){const outputDir=path.join(process.cwd(),'test-results',folder);fs.mkdirSync(outputDir,{recursive:true});await page.locator('#explanation-panel').screenshot({path:path.join(outputDir,`${String(rowIndex+1).padStart(2,'0')}-${safeName(rowValue)}.png`)})}
for(const form of FORMS){for(let rowIndex=0;rowIndex<ROW_COUNT;rowIndex++){test(`${form} explanation row ${String(rowIndex+1).padStart(2,'0')}`,async({page})=>{await generateFixture(page,form);const rowValue=await chooseRow(page,rowIndex);if(form==='past'||form==='passivePast')await assertPastLabels(page,rowIndex);else await assertPresentLabels(page,rowIndex);await shot(page,path.join('section01-explanations',FORM_DIRS[form]),rowIndex,rowValue)})}}
for(let rowIndex=0;rowIndex<ROW_COUNT;rowIndex++){test(`majzumPresent explanation row ${String(rowIndex+1).padStart(2,'0')}`,async({page})=>{await generateFixture(page,'majzumPresent','section02');const rowValue=await chooseRow(page,rowIndex);await assertMajzumLabels(page,rowIndex);await shot(page,path.join('section02-explanations','01-Majzum-Present'),rowIndex,rowValue)})}
for(let rowIndex=0;rowIndex<ROW_COUNT;rowIndex++){test(`mansubPresent explanation row ${String(rowIndex+1).padStart(2,'0')}`,async({page})=>{await generateFixture(page,'mansubPresent','section02');const rowValue=await chooseRow(page,rowIndex);await assertMansubLabels(page,rowIndex);await shot(page,path.join('section02-explanations','02-Mansub-Present'),rowIndex,rowValue)})}
for(let rowIndex=0;rowIndex<ROW_COUNT;rowIndex++){test(`heavyEmphatic explanation row ${String(rowIndex+1).padStart(2,'0')}`,async({page})=>{await generateFixture(page,'heavyEmphatic','section02');const rowValue=await chooseRow(page,rowIndex);await assertHeavyLabels(page,rowIndex);await shot(page,path.join('section02-explanations','03-Heavy-Emphasis'),rowIndex,rowValue)})}
for(let rowIndex=0;rowIndex<ROW_COUNT;rowIndex++){test(`lightEmphatic explanation row ${String(rowIndex+1).padStart(2,'0')}`,async({page})=>{await generateFixture(page,'lightEmphatic','section02');const rowValue=await chooseRow(page,rowIndex);await shot(page,path.join('section02-explanations','04-Light-Emphasis'),rowIndex,rowValue)})}
